change the order of test and seed

diff --git a/.github/workflows/synchronize_db.yaml b/.github/workflows/synchronize_db.yaml
--- a/.github/workflows/synchronize_db.yaml
+++ b/.github/workflows/synchronize_db.yaml
@@ -52,16 +52,16 @@ jobs:
         cd dbt_
         uv run dbt run || { echo "dbt run failed"; exit 1; }
 
+    - name: Seed data in dbt
+      run: |
+        cd dbt_
+        uv run dbt seed || { echo "dbt seed failed"; exit 1; }
+    
     - name: Test the data quality in dbt
       run: |
         cd dbt_
         uv run dbt test || { echo "dbt test failed"; exit 1; }
     
-    - name: Seed data in dbt
-      run: |
-        cd dbt_
-        uv run dbt seed || { echo "dbt seed failed"; exit 1; }
-
     - name: Upload production database to Storage
       run: |
         uv run pipelines/run.py run upload_database
