update sync

diff --git a/.github/workflows/synchronize_db.yaml b/.github/workflows/synchronize_db.yaml
--- a/.github/workflows/synchronize_db.yaml
+++ b/.github/workflows/synchronize_db.yaml
@@ -42,6 +42,21 @@ jobs:
       run: |
         uv run pipelines/run.py run build_database --refresh-type all --check-update
 
+    - name: Change direction to dbt folder
+      run: cd dbt
+      
+    - name: Install dbt dependencies
+      run: uv run dbt deps
+    
+    - name: Create tables/views in dbt
+      run: uv run dbt run || { echo "dbt run failed"; exit 1; }
+
+    - name: Test the data quality in dbt
+      run: uv run dbt test || || { echo "dbt seed failed"; exit 1; }
+    
+    - name: Seed data in dbt
+      run: uv run dbt seed
+
     - name: Upload production database to Storage
       run: |
         uv run pipelines/run.py run upload_database
