update syn

diff --git a/.github/workflows/synchronize_db.yaml b/.github/workflows/synchronize_db.yaml
--- a/.github/workflows/synchronize_db.yaml
+++ b/.github/workflows/synchronize_db.yaml
@@ -34,28 +34,31 @@ jobs:
     - name: Install dependencies
       run: uv sync 
 
-    - name: Download production database from Storage
-      run: |
-        uv run pipelines/run.py run download_database
+    # - name: Download production database from Storage
+    #   run: |
+    #     uv run pipelines/run.py run download_database
 
-    - name: Update production database
-      run: |
-        uv run pipelines/run.py run build_database --refresh-type all --check-update
+    # - name: Update production database
+    #   run: |
+    #     uv run pipelines/run.py run build_database --refresh-type all --check-update
 
     - name: Show --folder
-      run: ls -al
-      
-    - name: Change direction to dbt folder
+      run: ls -l
+
+    - name: Change direction to dbt_ folder
       run: cd dbt_
 
+    - name: Show --folder2
+      run: ls -l
+
     - name: Install dbt dependencies
-      run: uv run dbt deps
+      run: uv run dbt deps || { echo "dbt deps failed"; exit 1; }
     
     - name: Create tables/views in dbt
       run: uv run dbt run || { echo "dbt run failed"; exit 1; }
 
     - name: Test the data quality in dbt
-      run: uv run dbt test || || { echo "dbt seed failed"; exit 1; }
+      run: uv run dbt test || || { echo "dbt test failed"; exit 1; }
     
     - name: Seed data in dbt
       run: uv run dbt seed
